### ISSUE TITLE
6i6 both headphones output only on right channel

### ISSUE THREAD

**Issue by kunitoki** [smilingthax/alsa-driver_scarlett#4]
On my 6i6 only the right channel is active if i use the headphone (on both headphone outputs). I tried searching in alsamixer if there were an option regarding this but there is not.

**Comment by smilingthax** [comment]
It is possible that I got part of the control mapping or initial values wrong. 
But it should still be possible to make the output somewhat work, by playing with the routing controls and mixer volumes. I need to know exactly what "labels" do the wrong thing to make changes.
Also make sure you do output to the PCM1 and PCM2 channels (you can also try the other channels).

**Comment by kunitoki** [comment]
Ah no, it was my AKG headphones that stopped working as soon as i started testing the scarlett. Concidence i discovered this now when using them on my other soundcard, sorry for the mess
