### ISSUE TITLE
HW routing rewritten

### ISSUE THREAD

**Issue by lem8r** [smilingthax/alsa-driver_scarlett#6]
Hi! When I was testing this driver with my 18i20 all my HW roting was lost. Can I have my internal mixer setting left untouched untill I change smth by myself? I thought mixer driver have to read routing and other settings from sound card during startup not rewrite everything with some default settings.

**Comment by smilingthax** [comment]
Problem is, the Scarlett HW does not support reading the internal mixer settings -- you only read out some bogus values.
Therefore my driver has to cache the last set values per mixer to make even the usual use cases work.
Also the cache must be initialized somehow.
BTW, the Focusrite windows mixer app has the same behaviour. Try plugging your device into a second computer, and it will not show the settings done on the first one...
